include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

.deploy:
  variables:
    STACK: postgres
  environment:
    url: https://${CI_PROJECT_NAME}.${PUBLIC_HOSTNAME}
