include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

variables:
  STACK: postgres

.deploy:
  script:
    - >
      deploy.sh IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
      PGADMIN_SETUP_EMAIL=${PGADMIN_SETUP_EMAIL} PGADMIN_SETUP_PASSWORD=${PGADMIN_SETUP_PASSWORD}
      MAIL_SERVER=${MAIL_SERVER} MAIL_USER=${MAIL_USER} MAIL_PASSWORD=${MAIL_PASSWORD}
      PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
  environment:
    url: https://pgadmin.${PUBLIC_HOSTNAME}
