include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: main
    file: '/test/auto.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: main
    file: '/deploy/service/docker-deploy.yml'

stages:
  - deploy

.deploy:
  variables:
    STACK: postgres
