volumes:
  pgadmin-vol:
    name: ${PGADMIN_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}${PGADMIN_VOL_DEVICE:-/pgadmin-vol/}
