version: '3.5'

services:
  pgadmin:
    image: ${IMAGE_NAME:-dpage/pgadmin4}:${IMAGE_TAG:-latest}
    environment:
      PGADMIN_LISTEN_PORT:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD:
      PGADMIN_CONFIG_MAIL_SERVER:
      PGADMIN_CONFIG_MAIL_PORT:
      PGADMIN_CONFIG_MAIL_USE_SSL:
      PGADMIN_CONFIG_MAIL_USE_TLS:
      PGADMIN_CONFIG_MAIL_USERNAME:
      PGADMIN_CONFIG_MAIL_PASSWORD:
      PGADMIN_CONFIG_SECURITY_EMAIL_SENDER:
    networks:
      postgres-net:
      traefik-net:
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.frontend.rule: Host:${TRAEFIK_SUBDOMAIN:-pgadmin}.${PUBLIC_HOSTNAME}
        traefik.backend: pgadmin
        traefik.port: '${PGADMIN_LISTEN_PORT}'
      restart_policy:
        delay: ${RESTART_DELAY:-15s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-103M}

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
