version: '3.5'

services:
  pgadmin:
    image: ${IMAGE_NAME:-chorss/docker-pgadmin4}:${IMAGE_TAG:-latest}
    environment:
      - SERVER_MODE
      - PGADMIN_SETUP_EMAIL
      - PGADMIN_SETUP_PASSWORD
      - MAIL_SERVER
      - MAIL_PORT
      - MAIL_USE_TLS
      - MAIL_USER
      - MAIL_PASSWORD
    networks:
      - postgres-net
      - postgres-vessel-net
      - traefik-net
    volumes:
      - pgadmin-vol:/data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: Host:pgadmin.${PUBLIC_HOSTNAME}
        traefik.backend: pgadmin
        traefik.port: '${PGADMIN_PORT}'
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          memory: 103M

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    external: true
  postgres-vessel-net:
    name: ${POSTGRES_VESSEL_NET_NAME:-postgres-vessel-net}
    external: true
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  pgadmin-vol:
    name: ${PGADMIN_VOL_NAME:-pgadmin-vol}
