version: '3.5'

services:
  pgadmin:
    deploy:
      placement:
        constraints:
          - node.hostname == ${PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}

volumes:
  pgadmin-vol:
    name: ${PGADMIN_VOL_NAME:-pgadmin-vol}
