version: '3.5'

services:
  pgadmin:
    image: ${IMAGE_NAME:-chorss/docker-pgadmin4}:${IMAGE_TAG:-latest}
    environment:
      SERVER_MODE:
      PGADMIN_SETUP_EMAIL:
      PGADMIN_SETUP_PASSWORD:
      MAIL_SERVER:
      MAIL_PORT:
      MAIL_USE_TLS:
      MAIL_USER:
      MAIL_PASSWORD:
    networks:
      postgres-net:
      postgres-vessel-net:
      traefik-net:
    volumes:
      - pgadmin-vol:/data
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.frontend.rule: Host:pgadmin.${PUBLIC_HOSTNAME}
        traefik.backend: pgadmin
        traefik.port: '${PGADMIN_PORT}'
      restart_policy:
        delay: ${RESTART_DELAY:-30s}
      update_config:
        delay: ${UPDATE_DELAY:-2m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-103M}

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
